/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:050eb265-b85a-4e00-ac2c-63608882de87",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_k6NGrGszp",
    "aws_user_pools_web_client_id": "s3nu9ls6kjugtd0kter356c0t",
    "oauth": {}
};


export default awsmobile;
