/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ea7efe09-729b-4a54-8eca-9a31b41390b2",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_WYqhg1UZV",
    "aws_user_pools_web_client_id": "6f9tp16pa13adintcglrdo7rhd",
    "oauth": {}
};

export default awsmobile;
