/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:7bbfa951-fd14-4e62-8360-81bb778ad808",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_zziADg05u",
    "aws_user_pools_web_client_id": "7k6a27mitta26nsvvk16kk5mki",
    "oauth": {}
};


export default awsmobile;
