name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Manual trigger"
        required: true
        default: "Manually triggered build"

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: backend
        env:
          NODE_ENV: production
  publish_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and publish
        env:
          VUE_APP_BACKEND_SOCKET_ADDR: ${{ secrets.VUE_APP_BACKEND_SOCKET_ADDR }}
          VUE_APP_BACKEND_CHAT_MSG_ADDR: ${{ secrets.VUE_APP_BACKEND_CHAT_MSG_ADDR }}
        run: |
          cd frontend
          npm install
          npm publish
