name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual trigger'     
        required: true
        default: 'Manually triggered build' 

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: backend
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        env:
          CI: true
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_COGNITO_I_POOL_ID: ${{ secrets.AWS_COGNITO_I_POOL_ID }}
          AWS_COGNITO_REGION: ${{secrets.AWS_COGNITO_REGION}}
          AWS_COGNITO_U_POOL_ID: ${{ secrets.AWS_COGNITO_U_POOL_ID }}
          AWS_COGNITO_U_POOL_CLIENT_ID: ${{ secrets.AWS_COGNITO_U_POOL_CLIENT_ID }}
        run: |
          cd frontend 
          npm install
          NODE_ENV=production npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/frontend/dist
          CLEAN: true
          REPOSITORY_NAME: markiewiczjulian/chat_app_prod_ready